import sys
import os.path


'''To run this script you should pass a list of bam files, list of fragment length and a string (suffix file). This script generates the run.sh files to be submitted to HPC. The program to be used is postprocess.sh. This program generates the rawBW files from bam files. The postprocess.sh could be downloaded in https://github.com/IHEC/integrative_analysis_chip/tree/dev-organize-output/encode-wrapper/postprocess'''

'''If you do not want a new file name (just keep the original file name) you should to comment the follow lines:
suffix = sys.argv[3]
fn = fn.replace(suffix,'')
fn = fn + '-frag-' + fraglen + suffix'''


f_input = open(sys.argv[1], 'r') #list of bam files with root path
f_fraglen = open(sys.argv[2], 'r') #list of fragment length (i.e generated by spp program - xcorr IHEC ChIP-Seq pipeline

suffix = sys.argv[3] # suffix of file (i.e merged.bam)


#Add your account in SBATCH account
command_line = """#!/bin/bash
#SBATCH --time=72:00:00
#SBATCH --account= 
#SBATCH --mem=31G
#SBATCH --job-name=""" + "Raw-Bigwig-fraglen" +  "\nmodule load java/1.8 mugqic/deepTools/2.5.3 samtools/1.5\n"

print command_line

for line, fraglen in zip(f_input, f_fraglen):
     
     fraglen = str(fraglen.strip())
     dir_name = os.path.dirname(line)
     fn = os.path.basename(line.strip())
     fn = fn.replace(suffix,'')
     fn = fn + '-frag-' + fraglen + suffix
     fn = os.path.join(dir_name, fn)

     print"\nbash /PATH-TO-POSTPROCESS.sh/postprocess.sh " , fn , " " , fraglen  

  
